### ISSUE TITLE
Module build failed: TypeError: c.hslaString is not a function

### ISSUE THREAD

**Issue by aboe026** [ben-eb/colormin#42]
When i'm building with `postcss`, I receive the error originating from `colormin`:
```
ERROR in ./~/css-loader?sourceMap!./~/postcss-loader/lib?sourceMap!./~/sass-loader?sourceMap!./src/static/scss/common.scss
Module build failed: TypeError: c.hslaString is not a function
    at exports.default (<path/to/project>\node_modules\colormin\dist\index.js:59:26)
    at <path/to/project>\node_modules\postcss-colormin\dist\index.js:53:53
    at <path/to/project>\node_modules\postcss-colormin\dist\index.js:29:22
    at Array.forEach (<anonymous>)
    at walk (<path/to/project>\node_modules\postcss-colormin\dist\index.js:28:18)
    at transform (<path/to/project>\node_modules\postcss-colormin\dist\index.js:48:5)
    at <path/to/project>\node_modules\postcss-colormin\dist\index.js:74:20
    at <path/to/project>\node_modules\postcss\lib\container.js:192:28
    at <path/to/project>\node_modules\postcss\lib\container.js:148:26
    at Rule.each (<path/to/project>\node_modules\postcss\lib\container.js:114:22)
    at Rule.walk (<path/to/project>\node_modules\postcss\lib\container.js:147:21)
    at <path/to/project>\node_modules\postcss\lib\container.js:150:32
    at Root.each (<path/to/project>\node_modules\postcss\lib\container.js:114:22)
    at Root.walk (<path/to/project>\node_modules\postcss\lib\container.js:147:21)
    at Root.walkDecls (<path/to/project>\node_modules\postcss\lib\container.js:190:25)
    at <path/to/project>\node_modules\postcss-colormin\dist\index.js:73:20
    at LazyResult.run (<path/to/project>\node_modules\postcss\lib\lazy-result.js:274:20)
    at LazyResult.asyncTick (<path/to/project>\node_modules\postcss\lib\lazy-result.js:189:32)
    at LazyResult.asyncTick (<path/to/project>\node_modules\postcss\lib\lazy-result.js:201:22)
    at LazyResult.asyncTick (<path/to/project>\node_modules\postcss\lib\lazy-result.js:201:22)
    at LazyResult.asyncTick (<path/to/project>\node_modules\postcss\lib\lazy-result.js:201:22)
    at LazyResult.asyncTick (<path/to/project>\node_modules\postcss\lib\lazy-result.js:201:22)
    at LazyResult.asyncTick (<path/to/project>\node_modules\postcss\lib\lazy-result.js:201:22)
    at <path/to/project>\node_modules\postcss\lib\lazy-result.js:194:27
    at <anonymous>
 @ ./src/static/scss/common.scss 4:14-205
```

**Comment by senid231** [comment]
same thing here

doesn't know where to dig

@aboe026 did you find any solution?

**Comment by senid231** [comment]
I've found cause of this error

in my `package.json` I had wrong version of `colormin` in resolutions

I just remove it from `resolutions` and run `yarn install`

and everything works fine now
